package com.banking.system.customer.service.services;

import com.banking.system.customer.service.dtos.CustomerDto;
import org.springframework.data.domain.Page;

import java.time.LocalDate;

public interface CustomerService {


    /**
     * Creates Customer accounts - CustomerId is autogenerated, firstName and LastName are mandatory
     * @param customerDto Customer Details
     * @return CustomerDto - The dto is recreated after saving the customer
     */
    CustomerDto saveCustomer(CustomerDto customerDto);

    /**
     * @return A paginated list of customer
     * pageSize control number of customer returned
     * pageNo. controls the section of customer to be returned
     */
    Page<CustomerDto> getAllCustomers(int page, int size, String name, LocalDate startDate, LocalDate endDate);

    CustomerDto updateCustomer(Long customerId, CustomerDto dto);

    String deleteCustomer(Long customerId);

    CustomerDto getCustomerById(Long customerId);
}
